version: '3.7'

services:
  micro_01:
    build: 
      args:
        user: allan
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: laravel-app
    restart: unless-stopped
    work_dir: /var/www/
    volumes: ./:/var/www
